version: "3"

services:
  cmms-server:
    build: ./provisioning
    image: cmms
    depends_on:
      - mysql
      - node
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7@sha256:f568db3bdc3226cc28e4b148e6b9fd4e68d9c42e97a82be671bbe9eeb37ab1d5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:latest@sha256:1f9c00b4c95ef931afa097823d902e7602aebc3ec5532e907e066978075ca3e0
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/application/public:cached
    depends_on:
      - cmms-server

  node:
     image: node:latest@sha256:1201e1478ae2146ef699835a5726b1586e954b568962f5f937378d48de2e3014
     working_dir: /app
     ports:
       - "8080:8080"
     volumes:
      - ./:/app:cached