version: "3"

services:
  cmms-server:
    build: ./provisioning
    image: cmms
    depends_on:
      - mysql
      - node
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7@sha256:81679f23e0ece3e50a7300050191272e5afbf5b66be9b60d2ee0e8b575b152e2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:latest@sha256:edad5e71815c79108ddbd1d42123ee13ba2d8050ad27cfa72c531986d03ee4e7
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/application/public:cached
    depends_on:
      - cmms-server

  node:
     image: node:latest@sha256:1201e1478ae2146ef699835a5726b1586e954b568962f5f937378d48de2e3014
     working_dir: /app
     ports:
       - "8080:8080"
     volumes:
      - ./:/app:cached